In [3]:
import pandas as pd

In [8]:
list_of_orders = pd.read_csv('List of Orders.csv')
order_details = pd.read_csv('Order Details.csv')
sales_target = pd.read_csv('Sales target.csv')

In [18]:
# Ici, list_of_orders correspond à la liste des commandes réalisées sur le site de e-commerce
list_of_orders.head()

  Order ID  Order Date CustomerName           State       City
0  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad
1  B-25602  01-04-2018        Pearl     Maharashtra       Pune
2  B-25603  03-04-2018        Jahan  Madhya Pradesh     Bhopal
3  B-25604  03-04-2018       Divsha       Rajasthan     Jaipur
4  B-25605  05-04-2018      Kasheen     West Bengal    Kolkata

In [17]:
# Ici, order_details nous donne davantage d'informations sur la commande réalisée par le client
order_details.head()

  Order ID  Amount  Profit  Quantity     Category      Sub-Category
0  B-25601  1275.0 -1148.0         7    Furniture         Bookcases
1  B-25601    66.0   -12.0         5     Clothing             Stole
2  B-25601     8.0    -2.0         3     Clothing       Hankerchief
3  B-25601    80.0   -56.0         4  Electronics  Electronic Games
4  B-25602   168.0  -111.0         2  Electronics            Phones

In [64]:
# Le 3e dataset est plutôt un dataset d'objectif à réaliser
sales_target.head()

  Month of Order Date   Category   Target
0              Apr-18  Furniture  10400.0
1              May-18  Furniture  10500.0
2              Jun-18  Furniture  10600.0
3              Jul-18  Furniture  10800.0
4              Aug-18  Furniture  10900.0

In [20]:
list_of_orders.info(), list_of_orders.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    object
 1   Order Date    500 non-null    object
 2   CustomerName  500 non-null    object
 3   State         500 non-null    object
 4   City          500 non-null    object
dtypes: object(5)
memory usage: 22.0+ KB

(None,
 Order ID        60
 Order Date      60
 CustomerName    60
 State           60
 City            60
 dtype: int64)

In [22]:
order_details.info(), order_details.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   float64
 2   Profit        1500 non-null   float64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 70.4+ KB

(None,
 Order ID        0
 Amount          0
 Profit          0
 Quantity        0
 Category        0
 Sub-Category    0
 dtype: int64)

In [32]:
# Construisons un seul dataset à partir des 2 premiers pour avoir un peu plus de visibilité

df = list_of_orders.merge(order_details, on = 'Order ID')
df.head(10), df.shape

(  Order ID  Order Date CustomerName           State       City  Amount  \
 0  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad  1275.0
 1  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad    66.0
 2  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad     8.0
 3  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad    80.0
 4  B-25602  01-04-2018        Pearl     Maharashtra       Pune   168.0
 5  B-25602  01-04-2018        Pearl     Maharashtra       Pune   424.0
 6  B-25602  01-04-2018        Pearl     Maharashtra       Pune  2617.0
 7  B-25602  01-04-2018        Pearl     Maharashtra       Pune   561.0
 8  B-25602  01-04-2018        Pearl     Maharashtra       Pune   119.0
 9  B-25603  03-04-2018        Jahan  Madhya Pradesh     Bhopal  1355.0

    Profit  Quantity     Category      Sub-Category
 0 -1148.0         7    Furniture         Bookcases
 1   -12.0         5     Clothing             Stole
 2    -2.0         3     Clothing       Hankerchief
 3   -56.0         4  Electronics  Electronic Games
 4  -111.0         2  Electronics            Phones
 5  -272.0         5  Electronics            Phones
 6  1151.0         4  Electronics            Phones
 7   212.0         3     Clothing             Saree
 8    -5.0         8     Clothing             Saree
 9   -60.0         5     Clothing          Trousers  ,
 (1500, 10))

In [24]:
df.isna().sum()

Order ID        0
Order Date      0
CustomerName    0
State           0
City            0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
dtype: int64

In [38]:
# Définition correcte de la date dans le dataset + création d'une variable month et year

df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst = True)

df['Month'] = df['Order Date'].dt.month
df['Year'] = df['Order Date'].dt.year

df.head()

,Order ID,Order Date,CustomerName,State,City,Amount,Profit,Quantity,Category,Sub-Category,Month,Year
0,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,1275.0,-1148.0,7,Furniture,Bookcases,4,2018
1,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,66.0,-12.0,5,Clothing,Stole,4,2018
2,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,8.0,-2.0,3,Clothing,Hankerchief,4,2018
3,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,80.0,-56.0,4,Electronics,Electronic Games,4,2018
4,B-25602,2018-04-01,Pearl,Maharashtra,Pune,168.0,-111.0,2,Electronics,Phones,4,2018

In [66]:
# Maintenant regardons en détails les produits que l'on vend par catégorie, le CA et le profit associé

df_cat_sub = (df.groupby(['Category', 'Sub-Category'], as_index = False).agg({
    'Amount':'sum',
    'Quantity': 'sum',
    'Profit': 'sum'   
    })
)
df_cat_sub['Margin'] = df_cat_sub['Profit'] / df_cat_sub['Amount']
df_cat_sub

       Category      Sub-Category   Amount  Quantity  Profit    Margin
0      Clothing       Hankerchief  14608.0       754  2098.0  0.143620
1      Clothing             Kurti   3361.0       164   181.0  0.053853
2      Clothing          Leggings   2106.0       186   260.0  0.123457
3      Clothing             Saree  53511.0       782   352.0  0.006578
4      Clothing             Shirt   7555.0       271  1131.0  0.149702
5      Clothing             Skirt   1946.0       248   235.0  0.120761
6      Clothing             Stole  18546.0       671  2559.0  0.137981
7      Clothing           T-shirt   7382.0       305  1500.0  0.203197
8      Clothing          Trousers  30039.0       135  2847.0  0.094777
9   Electronics       Accessories  21728.0       262  3559.0  0.163798
10  Electronics  Electronic Games  39168.0       297 -1236.0 -0.031556
11  Electronics            Phones  46119.0       304  2207.0  0.047854
12  Electronics          Printers  58252.0       291  5964.0  0.102383
13    Furniture         Bookcases  56861.0       297  4888.0  0.085964
14    Furniture            Chairs  34222.0       277   577.0  0.016860
15    Furniture       Furnishings  13484.0       310   844.0  0.062593
16    Furniture            Tables  22614.0        61 -4011.0 -0.177368

In [67]:
# Insights business
# 1 - La sous-catégorie 'T-shirt' génère le plus de bénéfice
# 2 - Certaines sous-catégorie comme 'Printers', 'Bookcases' ou encore 'Saree' génèrent beaucoup de CA
# 3 - Certaines sous-catégorie se vendent à pertes

In [70]:
df_cat_sub_2 = (df.groupby(['Category', 'Sub-Category', 'Month', 'Year'], as_index = False).agg({
    'Amount':'sum',
    'Quantity': 'sum',
    'Profit': 'sum'   
    })
)
df_cat_sub_2['Margin'] = df_cat_sub_2['Profit'] / df_cat_sub_2['Amount']
df_cat_sub_2

      Category Sub-Category  Month  Year  Amount  Quantity  Profit    Margin
0     Clothing  Hankerchief      1  2019  2242.0       106   386.0  0.172168
1     Clothing  Hankerchief      2  2019  1862.0        71   381.0  0.204619
2     Clothing  Hankerchief      3  2019  2469.0       125   570.0  0.230863
3     Clothing  Hankerchief      4  2018  1116.0        54  -137.0 -0.122760
4     Clothing  Hankerchief      5  2018   299.0        37   -25.0 -0.083612
..         ...          ...    ...   ...     ...       ...     ...       ...
193  Furniture       Tables      6  2018  3444.0        11  -446.0 -0.129501
194  Furniture       Tables      9  2018  3614.0        11 -1974.0 -0.546209
195  Furniture       Tables     10  2018   632.0         4  -114.0 -0.180380
196  Furniture       Tables     11  2018  1987.0         6   273.0  0.137393
197  Furniture       Tables     12  2018  3394.0        10  -449.0 -0.132292

[198 rows x 8 columns]

In [71]:
df.to_csv('e_commerce_cleaned.csv', index = False)
df_cat_sub_2.to_csv('kpi_category_subcategory.csv', index = False)